project_id = "vlwwedprsjyxsnhponwd"

[functions.chat-products]
verify_jwt = false

[functions.generate-stand-visualization]
verify_jwt = false

[functions.generate-stand-image]
verify_jwt = false

[functions.generate-blog-article]
verify_jwt = false
